const fs=require('fs');
const app='src/App.tsx';
let s=fs.readFileSync(app,'utf8');
if(!s.includes('import SiteBuilder from "./SiteBuilder";')) s=s.replace('import "./admin.css";','import "./admin.css";\nimport SiteBuilder from "./SiteBuilder";');
const nav='const nav=[{id:"dashboard",label:"Обзор",icon:<Package size={17}/>},{id:"products",label:"Товары",icon:<Package size={17}/>},{id:"categories",label:"Категории",icon:<Users size={17}/>},{id:"reviews",label:"Отзывы",icon:<Star size={17}/>},{id:"orders",label:"Заказы",icon:<RefreshCw size={17}/>},{id:"settings",label:"Настройки",icon:<Settings size={17}/>}] as const;';
const navNew='const nav=[{id:"dashboard",label:"Обзор",icon:<Package size={17}/>},{id:"products",label:"Товары",icon:<Package size={17}/>},{id:"categories",label:"Категории",icon:<Users size={17}/>},{id:"reviews",label:"Отзывы",icon:<Star size={17}/>},{id:"orders",label:"Заказы",icon:<RefreshCw size={17}/>},{id:"settings",label:"Настройки",icon:<Settings size={17}/>},{id:"builder",label:"Конструктор",icon:<Settings size={17}/>} ] as const;';
if(s.includes(nav)) s=s.replace(nav,navNew);
const render='{section==="settings"&&<SettingsPanel value={settings} onSubmit={saveSettings}/>}';
if(s.includes(render) && !s.includes('{section==="builder"&&<SiteBuilder/>}')) s=s.replace(render,render+' {section==="builder"&&<SiteBuilder/>}');
fs.writeFileSync(app,s);
const pub='src/PublicBoutique.tsx';
let p=fs.readFileSync(pub,'utf8');
const old='const [siteSections,setSiteSections]=useState<any[]>([]);useEffect(()=>{let alive=true;(async()=>{const {data}=await supabase.from("site_builder").select("sections").eq("id",true).maybeSingle();if(!alive||!data)return;const sections=Array.isArray(data.sections)?data.sections:[];const order={hero:0,categories:1,about:2,bestsellers:3,delivery:4,reviews:5,contacts:6};const nodes=Array.from(document.querySelectorAll("#top main > section"));const indexToId=["hero","categories","about","about-extra","bestsellers","delivery","reviews","contacts"];const byId=new Map(sections.map((x:any)=>[x.id,x]));const main=document.querySelector("#top main") as HTMLElement|null;if(main){main.style.display="flex";main.style.flexDirection="column";nodes.forEach((node,i)=>{const id=indexToId[i];const cfg=byId.get(id);if(cfg){node.style.display=cfg.visible===false?"none":"";node.style.order=String(sections.indexOf(cfg));}else{node.style.order=String(100+i)}})}})();return()=>{alive=false}},[]);';
const newer='useEffect(()=>{let alive=true;(async()=>{const {data}=await supabase.from("site_builder").select("sections").eq("id",true).maybeSingle();if(!alive||!data)return;const sections=Array.isArray(data.sections)?data.sections:[];const nodes=Array.from(document.querySelectorAll("#top main > section"));const indexToId=["hero","categories","about","about-extra","bestsellers","delivery","reviews","contacts"];const byId=new Map(sections.map((x:any)=>[x.id,x]));const main=document.querySelector("#top main") as HTMLElement|null;if(main){main.style.display="flex";main.style.flexDirection="column";nodes.forEach((node,i)=>{const id=indexToId[i];const cfg=byId.get(id);if(cfg){node.style.display=cfg.visible===false?"none":"";node.style.order=String(sections.indexOf(cfg));}else{node.style.order=String(100+i)}})}})();return()=>{alive=false}},[]);';
p=p.replace(old,new);
if(!p.includes('const indexToId=["hero","categories"')){const needle='const [floristSent,setFloristSent]=useState(false);const [floristBusy,setFloristBusy]=useState(false);';p=p.replace(needle,needle+newer)}
fs.writeFileSync(pub,p);
console.log('site builder wired for admin and public layout');