import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowRight, Gift, HeartHandshake, MapPin, Menu, Phone, ShieldCheck, ShoppingBag, Truck, X } from "lucide-react";
import { supabase } from "./lib/supabase";

const fallbackImages = [
  "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=1400&q=88",
  "https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=1400&q=88",
  "https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=1400&q=88",
  "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=1400&q=88",
  "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1400&q=88",
  "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1400&q=88",
];

type Product = { id:string; slug:string; name:string; description:string; short_description:string|null; price:number|null; old_price:number|null; category_id:string|null; main_image:string|null; images:string[]; alt:string|null; is_active:boolean; is_featured:boolean; sort_order:number };
type Category = { id:string; name:string; slug:string };
type Review = { id:string; name:string; rating:number|null; body:string; source:string|null };
type StoreSettings = { id:boolean; store_name:string; address:string; phone_1:string; phone_2:string; whatsapp_url:string|null; telegram_url:string|null; max_url:string|null; working_days:string; working_from:string; working_to:string; delivery_method:string; latitude:number; longitude:number };
const defaultSettings:StoreSettings={id:true,store_name:"Студия Цветов",address:"улица Невельского, 3Ак4, Новосибирск",phone_1:"+7 (952) 916-52-15",phone_2:"+7 (993) 028-49-94",whatsapp_url:"https://wa.me/79529165215",telegram_url:"tg://resolve?phone=79529165215",max_url:null,working_days:"Ежедневно",working_from:"09:00",working_to:"21:30",delivery_method:"Яндекс Доставка",latitude:54.993045,longitude:82.833637};
function money(value:number|null){return value==null?"Цена по запросу":`${value.toLocaleString("ru-RU")} ₽`}
function imageFor(product:Product,index=0){return product.main_image||product.images?.[0]||fallbackImages[index%fallbackImages.length]}
function routeUrl(settings:StoreSettings){return `https://yandex.ru/maps/?rtext=~${settings.latitude}%2C${settings.longitude}&rtt=auto`}
function useBoutiqueData(){const [products,setProducts]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [settings,setSettings]=useState<StoreSettings>(defaultSettings);const [loading,setLoading]=useState(true);useEffect(()=>{let active=true;async function load(){if(!supabase){setLoading(false);return}const [p,c,r,s]=await Promise.all([supabase.from("products").select("*").eq("is_active",true).order("sort_order"),supabase.from("categories").select("id,name,slug").eq("is_active",true).order("sort_order"),supabase.from("reviews").select("id,name,rating,body,source").eq("is_published",true).order("created_at",{ascending:false}),supabase.from("store_settings").select("*").eq("id",true).maybeSingle()]);if(!active)return;if(!p.error)setProducts((p.data||[]) as Product[]);if(!c.error)setCategories((c.data||[]) as Category[]);if(!r.error)setReviews((r.data||[]) as Review[]);if(!s.error&&s.data)setSettings(s.data as StoreSettings);setLoading(false)}void load();return()=>{active=false}},[]);return{products,categories,reviews,settings,loading}}
function Header({settings}:{settings:StoreSettings}){const [open,setOpen]=useState(false);const links=[["О нас","about"],["Каталог","catalog"],["Отзывы","reviews"],["Контакты","contacts"]] as const;return <header className="boutique-header"><a className="boutique-logo" href="#top">СТУДИЯ <span>ЦВЕТОВ</span></a><nav className="boutique-nav">{links.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><a className="boutique-header-phone" href={`tel:${settings.phone_1.replace(/\D/g,"")}`}>{settings.phone_1}</a><button className="boutique-menu" onClick={()=>setOpen(v=>!v)} aria-label="Меню">{open?<X/>:<Menu/>}</button>{open&&<div className="boutique-mobile-nav">{links.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}<a href={settings.whatsapp_url||"#"}>WhatsApp</a><a href={settings.telegram_url||"#"}>Telegram</a></div>}</header>}
function Button({children,onClick,outline=false,type="button"}:{children:React.ReactNode;onClick?:()=>void;outline?:boolean;type?:"button"|"submit"}){return <button type={type} className={`boutique-button ${outline?"boutique-button--outline":""}`} onClick={onClick}>{children}</button>}
export default function PublicBoutique(){const {products,categories,reviews,settings,loading}=useBoutiqueData();const [selected,setSelected]=useState<Product|null>(null);const [bestIndex,setBestIndex]=useState(0);const [formSent,setFormSent]=useState(false);const [formBusy,setFormBusy]=useState(false);const [floristSent,setFloristSent]=useState(false);const [floristBusy,setFloristBusy]=useState(false);const visibleProducts=products.slice(0,6);const featured=useMemo(()=>((products.filter(p=>p.is_featured).length?products.filter(p=>p.is_featured):products).slice(0,Math.max(3,products.length))),[products]);const best=featured.length?featured:visibleProducts;const bestProduct=best[bestIndex%Math.max(1,best.length)];const bestPrev=best.length?best[(bestIndex-1+best.length)%best.length]:null;const bestNext=best.length?best[(bestIndex+1)%best.length]:null;
async function submitProductOrder(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!selected)return;setFormBusy(true);const fd=new FormData(e.currentTarget);const {error}=await supabase.from("orders").insert({customer_name:String(fd.get("name")||""),customer_phone:String(fd.get("phone")||""),customer_message:String(fd.get("message")||""),product_id:selected.id,product_name:selected.name,amount:selected.price,payload:Object.fromEntries(fd.entries())});setFormBusy(false);if(!error)setFormSent(true)}
async function submitFlorist(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setFloristBusy(true);const fd=new FormData(e.currentTarget);const {error}=await supabase.from("orders").insert({customer_name:String(fd.get("name")||""),customer_phone:String(fd.get("phone")||""),customer_message:String(fd.get("comment")||""),product_name:"Помощь флориста",amount:null,payload:Object.fromEntries(fd.entries())});setFloristBusy(false);if(!error){setFloristSent(true);e.currentTarget.reset()}}
return <div className="boutique-site" id="top"><Header settings={settings}/><main>
<section className="boutique-hero"><div className="boutique-hero-copy"><p className="boutique-eyebrow">СТУДИЯ ЦВЕТОВ · НОВОСИБИРСК</p><h1>Доставка<br/>букетов<br/>на заказ</h1><p>Собираем цветы вручную и доставляем их по Новосибирску. Поможем выбрать букет для любого повода.</p><div className="boutique-hero-actions"><Button outline onClick={()=>document.getElementById("delivery")?.scrollIntoView({behavior:"smooth"})}>Подробнее</Button><Button onClick={()=>document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"})}>Выбрать букет</Button></div><div className="boutique-hero-line"><span/><i/></div></div><div className="boutique-hero-image"><img src={imageFor(best[0]||({main_image:null,images:[]} as Product),0)} alt="Букет Студии Цветов"/></div></section>
<section className="boutique-section boutique-catalog" id="catalog"><div className="boutique-section-heading"><span>Каталог</span><em/></div><p className="boutique-section-sub">Готовые букеты, которые можно заказать сегодня</p>{loading?<div className="boutique-loading">Загружаем каталог…</div>:<div className="boutique-grid">{visibleProducts.map((p,i)=><button key={p.id} className="boutique-product" onClick={()=>setSelected(p)}><span className="boutique-product-image"><img src={imageFor(p,i)} alt={p.alt||p.name}/></span><span className="boutique-product-meta"><span><strong>{p.name}</strong><small>{categories.find(c=>c.id===p.category_id)?.name||"Букет"}</small></span><b>{money(p.price)}</b><ShoppingBag size={23} strokeWidth={1.65}/></span></button>)}</div>}<Button onClick={()=>document.getElementById("bestsellers")?.scrollIntoView({behavior:"smooth"})}>Открыть ещё</Button></section>
<section className="boutique-section boutique-why" id="about"><div className="boutique-section-heading"><span>Почему именно мы?</span><em/></div><p className="boutique-section-sub">Наши букеты дарят вам самые яркие эмоции</p><div className="boutique-why-grid"><div className="boutique-why-photo"><img src={imageFor(products[3]||products[0]||({main_image:null,images:[]} as Product),3)} alt="Авторский букет"/></div><div className="boutique-reasons"><article><HeartHandshake size={36} strokeWidth={1.2}/><h3>Доверие</h3><p>Внимательно собираем каждый заказ и остаёмся на связи.</p></article><article><Truck size={36} strokeWidth={1.2}/><h3>Доставка</h3><p>Передаём букеты через Яндекс Доставку в удобное время.</p></article><article><ShieldCheck size={36} strokeWidth={1.2}/><h3>Качество</h3><p>Работаем со свежими цветами и тщательно проверяем каждый букет.</p></article><article><Gift size={36} strokeWidth={1.2}/><h3>Подарок</h3><p>Поможем подобрать открытку и красивое оформление к заказу.</p></article></div></div></section>
<section className="boutique-about-block"><div className="boutique-about-text"><p>«СТУДИЯ ЦВЕТОВ» — пространство, где цветы помогают сказать самое важное.</p><p>Мы собираем букеты с вниманием к цвету, форме и настроению получателя.</p></div><div className="boutique-about-photo"><img src={imageFor(products[4]||products[0]||({main_image:null,images:[]} as Product),4)} alt="Цветочная композиция"/></div></section>
<section className="boutique-section boutique-bestsellers" id="bestsellers"><div className="boutique-section-heading"><span>Бестселлеры</span><em/></div><div className="boutique-carousel">{bestPrev?<button className="boutique-side-product" onClick={()=>setBestIndex((bestIndex-1+best.length)%best.length)}><img src={imageFor(bestPrev,1)} alt={bestPrev.name}/><strong>{bestPrev.name}</strong><small>{money(bestPrev.price)}</small></button>:<div/>}<article className="boutique-best-main"><img src={imageFor(bestProduct||({main_image:null,images:[]} as Product),2)} alt={bestProduct?.name||"Букет"}/><div><h3>{bestProduct?.name||"Букет"}</h3><b>{money(bestProduct?.price??null)}</b><p>{bestProduct?.short_description||"Авторский букет для особенного повода."}</p><Button onClick={()=>bestProduct&&setSelected(bestProduct)}>В корзину</Button></div></article>{bestNext?<button className="boutique-side-product" onClick={()=>setBestIndex((bestIndex+1)%best.length)}><img src={imageFor(bestNext,3)} alt={bestNext.name}/><strong>{bestNext.name}</strong><small>{money(bestNext.price)}</small></button>:<div/>}</div><div className="boutique-dots">{best.slice(0,Math.min(5,best.length)).map((_,i)=><button key={i} className={i===bestIndex%5?"active":""} onClick={()=>setBestIndex(i)} aria-label={`Бестселлер ${i+1}`}/>)}</div></section>
<section className="boutique-florist" id="delivery"><div className="boutique-florist-copy"><div className="boutique-section-heading"><span>Не подобрали подходящий букет?</span><em/></div><p>Соберём букет лично для вас.</p><p className="boutique-muted">Оставьте контакты — флорист уточнит пожелания и предложит варианты.</p></div><div className="boutique-florist-photo"><img src={imageFor(products[1]||products[0]||({main_image:null,images:[]} as Product),1)} alt="Помощь флориста"/><form onSubmit={submitFlorist} className="boutique-glass-form"><h3>Оставьте свои контактные данные</h3><p>Мы свяжемся с вами и поможем выбрать композицию.</p><input name="name" placeholder="Имя" required/><input name="phone" placeholder="Телефон" required/><textarea name="comment" placeholder="Пожелания" rows={3}/><Button type="submit">{floristBusy?"Отправляем…":"Оставить заявку"}</Button>{floristSent&&<span className="boutique-form-success">Заявка отправлена — скоро свяжемся с вами.</span>}</form></div></section>
<section className="boutique-section boutique-reviews" id="reviews"><div className="boutique-section-heading"><span>Отзывы</span><em/></div>{reviews.length?<div className="boutique-review-grid">{reviews.slice(0,3).map(r=><article key={r.id}><div className="boutique-avatar">{r.name.slice(0,1)}</div><h3>{r.name}</h3><div className="boutique-stars">{Array.from({length:r.rating||5}).map((_,i)=><span key={i}>★</span>)}</div><p>{r.body}</p><small>{r.source||"Клиент Студии Цветов"}</small></article>)}</div>:<div className="boutique-empty-reviews">Реальные отзывы клиентов появятся здесь после публикации из админ-панели.</div>}</section>
<section className="boutique-section boutique-contacts" id="contacts"><div><div className="boutique-section-heading"><span>Контакты</span><em/></div><h2>Будем рады<br/>собрать цветы<br/>для вас</h2><p>{settings.address}</p><p>{settings.working_days} · {settings.working_from}–{settings.working_to}</p><a href={routeUrl(settings)} target="_blank" rel="noreferrer">Построить маршрут <ArrowRight size={16}/></a></div><div className="boutique-contact-list"><a href={`tel:${settings.phone_1.replace(/\D/g,"")}`}><Phone size={18}/>{settings.phone_1}</a><a href={`tel:${settings.phone_2.replace(/\D/g,"")}`}><Phone size={18}/>{settings.phone_2}</a><a href={settings.whatsapp_url||"#"}>WhatsApp</a><a href={settings.telegram_url||"#"}>Telegram</a></div></section></main>
<footer className="boutique-footer"><div className="boutique-footer-brand"><a className="boutique-logo boutique-logo--light" href="#top">СТУДИЯ <span>ЦВЕТОВ</span></a><p>Цветы с доставкой по Новосибирску.</p></div><div><h4>Информация</h4><a href="#about">О нас</a><a href="#catalog">Каталог</a><a href="#reviews">Отзывы</a></div><div><h4>Поддержка</h4><a href="#delivery">Помощь флориста</a><a href="#contacts">Доставка</a><a href="#contacts">Контакты</a></div><div><h4>Часы работы</h4><p>{settings.working_days}</p><p>{settings.working_from}–{settings.working_to}</p><a href={`tel:${settings.phone_1.replace(/\D/g,"")}`}>{settings.phone_1}</a></div></footer>
{selected&&<div className="boutique-modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="boutique-modal" onMouseDown={e=>e.stopPropagation()}>{formSent?<><div className="boutique-check">✓</div><h2>Заявка отправлена</h2><p>Спасибо. Мы свяжемся с вами для подтверждения заказа.</p><Button onClick={()=>{setFormSent(false);setSelected(null)}}>Закрыть</Button></>:<><button className="boutique-modal-close" onClick={()=>setSelected(null)} aria-label="Закрыть"><X/></button><img src={imageFor(selected)} alt={selected.alt||selected.name}/><div className="boutique-modal-copy"><span className="boutique-eyebrow">БУКЕТ</span><h2>{selected.name}</h2><b>{money(selected.price)}</b><p>{selected.description||selected.short_description||"Свежая цветочная композиция, собранная вручную."}</p><form onSubmit={submitProductOrder}><input name="name" placeholder="Имя" required/><input name="phone" placeholder="Телефон" required/><textarea name="message" placeholder="Комментарий" rows={3}/><Button type="submit">{formBusy?"Отправляем…":"Заказать букет"}</Button></form></div></>}</div></div>}
</div>}
