import { useEffect, useState } from "react";
import { GripVertical, Eye, EyeOff, Save, RotateCcw, Plus, Trash2 } from "lucide-react";
import { supabase } from "./lib/supabase";

type Section={id:string;title:string;visible:boolean};
type Theme={background?:string;accent?:string;radius?:number};
const defaults:Section[]=[
 {id:"hero",title:"Первый экран",visible:true},{id:"bestsellers",title:"Бестселлеры",visible:true},{id:"categories",title:"Категории",visible:true},{id:"about",title:"О магазине",visible:true},{id:"delivery",title:"Доставка",visible:true},{id:"reviews",title:"Отзывы",visible:true},{id:"contacts",title:"Контакты",visible:true}
];
export default function SiteBuilder(){
 const [sections,setSections]=useState<Section[]>(defaults); const [theme,setTheme]=useState<Theme>({background:"#f8f3ef",accent:"#5e4940",radius:16}); const [busy,setBusy]=useState(true); const [notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{const {data}=await supabase.from("site_builder").select("sections,theme").eq("id",true).maybeSingle();if(data){setSections(Array.isArray(data.sections)?data.sections:defaults);setTheme(data.theme||{})}setBusy(false)})()},[]);
 async function save(){setBusy(true);const {error}=await supabase.from("site_builder").update({sections,theme,updated_at:new Date().toISOString()}).eq("id",true);setBusy(false);setNotice(error?error.message:"Настройки конструктора сохранены");setTimeout(()=>setNotice(""),2500)}
 function move(i:number,d:number){const a=[...sections],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setSections(a)}
 function add(){const id=`custom-${Date.now()}`;setSections([...sections,{id,title:"Новый раздел",visible:true}])}
 function reset(){if(confirm("Вернуть стандартный порядок разделов?"))setSections(defaults)}
 return <div className="admin-content"><div className="builder-head"><div><h2>Конструктор сайта</h2><p>Перетаскивайте разделы, меняйте названия и включайте или скрывайте блоки.</p></div><div className="builder-actions"><button className="admin-btn" onClick={reset}><RotateCcw size={16}/>Сбросить</button><button className="admin-btn" onClick={add}><Plus size={16}/>Раздел</button><button className="admin-btn admin-btn--primary" onClick={save} disabled={busy}><Save size={16}/>Сохранить</button></div></div>{notice&&<div className="admin-notice">{notice}</div>}<div className="builder-layout"><section className="panel"><div className="panel-head"><div><h2>Структура главной</h2><p>Порядок сверху вниз</p></div></div><div className="builder-list">{sections.map((s,i)=><div className={`builder-row ${!s.visible?"is-hidden":""}`} key={s.id}><GripVertical size={18}/><div className="builder-order"><button disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button disabled={i===sections.length-1} onClick={()=>move(i,1)}>↓</button></div><input value={s.title} onChange={e=>setSections(sections.map(x=>x.id===s.id?{...x,title:e.target.value}:x))}/><button className="builder-icon" onClick={()=>setSections(sections.map(x=>x.id===s.id?{...x,visible:!x.visible}:x))}>{s.visible?<Eye size={17}/>:<EyeOff size={17}/>}</button>{s.id.startsWith("custom-")&&<button className="builder-icon danger" onClick={()=>setSections(sections.filter(x=>x.id!==s.id))}><Trash2 size={17}/></button>}</div>)}</div></section><aside className="panel"><div className="panel-head"><div><h2>Оформление</h2><p>Базовые параметры темы</p></div></div><div className="builder-theme"><label>Фон<input type="text" value={theme.background||""} onChange={e=>setTheme({...theme,background:e.target.value})}/></label><label>Акцент<input type="text" value={theme.accent||""} onChange={e=>setTheme({...theme,accent:e.target.value})}/></label><label>Скругление карточек<input type="number" min="0" max="40" value={theme.radius??16} onChange={e=>setTheme({...theme,radius:Number(e.target.value)})}/></label><div className="builder-preview" style={{background:theme.background,borderRadius:theme.radius}}><strong>Предпросмотр</strong><span style={{color:theme.accent}}>Студия Цветов</span><small>Изменения сохраняются в настройках магазина.</small></div></div></aside></div></div>
}